### ISSUE TITLE
Add Some Notes From Running?

### ISSUE THREAD

**Issue by JZL** [0xERR0R/mailcatcher#5]
Hi,

I was hoping to use something exactly like this, so it's great that this already exists. Thanks for writing it!

A few things I hit getting it writing which might be helpful to someone else (if they find this error or to add to the README?)

- I was using a little cloud VPS so it's not as easy to set up port forwarding like you mention, I was just going to use port 25 straight. After a lot of errors, it turns out you can't use `25:25` in the docker-compose.yml, you have to use *quoted* `"25:25"`. Strange
- For using GMail SMTP, you also have to turn insecure apps on https://support.google.com/accounts/answer/6010255?hl=en . I thought there was a way to have a per-application password to make it more secure but didn't look more (I'll just use a throwaway account to forward). You also have to wait 30 minutes for it percolate
- When you convert incoming `To:` -> `From:` ([here](https://github.com/0xERR0R/mailcatcher/blob/f86903b8383e0f14ee9ef42a7314085408bf0a83/cmd/mailcatcher/server.go#L55)), I had issues if the `To:` email already includes a name. So if the incoming email has `To: John <john@john.com>` it is converted to `From: John <john@john.com> <ultimate@dest.com>` and GMail doesn't always appreciate two sets of brackets. I can give a PR, I don't know Golang well so I just regexp'd removed `[<>]` away. 
- A GMail fact I've hit over and over and forget each time when debugging. Maybe it'll save someone else some trouble. Say `MC_REDIRECT_TO=john@john.com` and `MC_HOST=throw@away.com`. If you send from john@john.com -> throw@away.com it will silently stop before it sends a duplicate back to john again. Many SMTP providers including gmail use the Message-ID to prevent loops, so it'll just silently drop the email. Using mailinator/similar as `MC_REDIRECT_TO` is better for the initial debugging

**Comment by 0xERR0R** [comment]
Thank you for your feedback! I have just seen this issue, my bad 😕. I wrote this small tool just for fun (and for me of course) and I'm very glad, that somebody uses it.

Regarding the port: yes, you can of course use port 25. On my system, this port was already in use. You can also try to run your container with "host" network mode, this will bind ports directly and you don't need any port forwardings.

Regarding the GMail SMTP limitation -> thanks for this information, I think you're right, I'll add it to the README.

Regarding other points: PRs are always welcome, please feel free to contribute 👍
